let num1 = parseInt(prompt("Digite um número inteiro: "))

console.log(`1 x ${num1} = ${num1 * 1}`)
console.log(`2 x ${num1} = ${num1 * 2}`)
console.log(`3 x ${num1} = ${num1 * 3}`)
console.log(`4 x ${num1} = ${num1 * 4}`)
console.log(`5 x ${num1} = ${num1 * 5}`)
console.log(`6 x ${num1} = ${num1 * 6}`)
console.log(`7 x ${num1} = ${num1 * 7}`)
console.log(`8 x ${num1} = ${num1 * 8}`)
console.log(`9 x ${num1} = ${num1 * 9}`)
console.log(`10 x ${num1} = ${num1 * 10}`)